Details={
    "Main_Location":"/home/pi/NFC",
    "username_mqtt":"iocld-mqtt-admin",
    "password_mqtt":"admin123",
    "mqtt_broker":"192.168.1.222",
    "mqtt_port":1883,
    "Publish_Topic":"AI/IIOT/IOCLD/NFC/",
    "HeartBeat_Topic_Suffix":"/STATUS",
    "Data_Topic_Suffix":"/DATA",
    "HB_time":60,
    "Main_Loop_Interval":0.2
}