Details={
    "Main_Location":"/home/pi/NFC",
    "username_mqtt":"innv3-ncr-hdfc",
    "password_mqtt":"Rs502a*mcJ9z0Z",
    "mqtt_broker":"broker.hivemq.com",
    "mqtt_port":1883,
    "Publish_Topic":"AI/IIOT/IOCLD/NFC/",
    "HeartBeat_Topic_Suffix":"/STATUS",
    "Data_Topic_Suffix":"/DATA"
}